# Generated by Django 5.2 on 2025-04-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateOrder',
        ),
    ]
